### ISSUE TITLE
 flicker of the unfolding div in chrome

### ISSUE THREAD

**Issue by josephcf** [codrops/PFold#5]
hi, I have this problem with chrome, could this be fixed or is it a technical limitation

**Comment by tbredin** [comment]
I just pushed the back away by 1px and then forced a composite - this fixed it for me!

SCSS:

```
.uc-part {
        .uc-back {
            transform: rotateY(-180deg) translateZ(1px);
        }
        > div {
            transform: translateZ(0);
        }
}
```

**Comment by botelho** [comment]
I guess it's solved. Thanks guys!
